version: '3.7'
services:
 db:
  container_name: ${MYSQL_CONTAINER_NAME}
  image: ${MYSQL_IMAGE_VERSION}
  volumes:
   - db_data:/var/lib/mysql
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
   MYSQL_DATABASE: ${MYSQL_DATABASE}
   MYSQL_USER: ${MYSQL_USER}
   MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  networks:
   db_net:
    ipv4_address: 172.16.238.10
    ipv6_address: 2001:3984:3989::10
 wordpress:
  container_name: ${WORDPRESS_CONTAINER_NAME}
  depends_on:
   - db
  image: ${WORDPRESS_IMAGE_VERSION}
  ports:
   - target: 80
     published: 8080
     protocol: tcp
     mode: host
  restart: always
  volumes:
   - wp_files:/var/www/html
  environment:
   WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
   WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
   WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
   WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
  networks:
   wordpress_net:
    ipv4_address: 172.16.238.10
    ipv6_address: 2001:3984:3989::10
volumes:
 db_data:
 wp_files:
networks:
 wordpress_net:
  ipam:
   driver: default
   config:
    - subnet: 172.16.238.0/24
    - subnet: "2001:3984:3989::/64"
db_net:
  ipam:
   driver: default
   config:
    - subnet: 172.16.238.0/24
    - subnet: "2001:3984:3989::/64"
